version: '3.8'

services:
  backend:
    container_name: studymate-backend
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # 1. Ghi đè URL Database (Thay localhost bằng tên service 'db')
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/studymate_db

      # 2. Map biến từ .env vào tên biến mà Spring Boot chờ đợi
      # Cú pháp: TÊN_BIẾN_TRONG_JAVA=${TÊN_BIẾN_TRONG_FILE_ENV}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

      # 3. Quan trọng nhất: Bơm SIGNER_KEY vào
      - SIGNER_KEY=${SIGNER_KEY}
      - APP_JWT_EXPIRATION_MS=${APP_JWT_EXPIRATION_MS}

      # 4. Frontend URL
      - FRONTEND_URL=${FRONTEND_URL}

    depends_on:
      - db
    networks:
      - studymate-network
    restart: always

  db:
    image: postgres:16-alpine
    container_name: studymate-db
    environment:
      POSTGRES_DB: studymate_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - studymate-network
    restart: always

networks:
  studymate-network:
    driver: bridge

volumes:
  postgres_data: