spring.application.name=studymate-backend
server.port=8080
# --- Database ---
# M?c ??nh là localhost cho lúc code, lên Docker s? t? nh?n bi?n môi tr??ng ?è vào
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/studymate}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver
# --- JPA/Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# --- JWT Security ---
app.jwt.signer-key=${SIGNER_KEY}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:10800000}
# --- Email Service ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# --- Gemini AI ---
gemini.api.key=${GEMINI_API_KEY}
# --- PayOS ---
payos.client-id=${PAYOS_CLIENT_ID}
payos.api-key=${PAYOS_API_KEY}
payos.checksum-key=${PAYOS_CHECKSUM_KEY}
# --- Domain Frontend ---
app.frontend-url=${FRONTEND_URL:https://studymate-frontend-murex.vercel.app}